import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="mb-2 text-lg font-semibold text-slate-100">{title}</h2>
      <div className="space-y-3 text-sm leading-relaxed text-muted">{children}</div>
    </section>
  );
}

export default function MethodologyPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <Header />
      <main className="flex-1">
        <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6">
          <Link href="/" className="text-xs text-accent hover:underline">
            ← Back
          </Link>
          <h1 className="mb-6 mt-3 text-2xl font-bold text-slate-50">Methodology &amp; data sources</h1>
          <p className="mb-8 text-sm leading-relaxed text-muted">
            Every number ChartPilot shows you is produced by a named, standard formula or a
            real fetched price bar — nothing is generated by an opaque model guessing at what a
            chart "looks like." This page explains exactly how, so you can judge how much to
            trust it yourself.
          </p>

          <Section title="1. Reading your screenshot">
            <p>
              When you upload an image, two independent things happen in your browser (the
              image is not required to leave your device for this step):
            </p>
            <ul className="list-disc space-y-1.5 pl-5">
              <li>
                <strong className="text-slate-300">OCR ticker detection</strong> — Tesseract.js
                (a free, open-source OCR engine) reads any text in the image and looks for
                ticker-like tokens. This is a best-effort auto-fill, not a guarantee — always
                confirm or type the ticker yourself for the most reliable result.
              </li>
              <li>
                <strong className="text-slate-300">Visual heuristics</strong> — a canvas-based
                pass estimates the ratio of green vs red chart coloring and fits a trend line
                across the image to guess direction. This is intentionally treated as a weak,
                low-confidence signal (see "Confidence scoring" below) and is only used as the
                primary signal when no ticker can be resolved to real data.
              </li>
            </ul>
          </Section>

          <Section title="2. Getting real price data">
            <p>
              If a ticker is available (typed or detected), ChartPilot fetches real historical
              price bars from free, public, unauthenticated endpoints — no paid data vendor,
              no API key:
            </p>
            <ul className="list-disc space-y-1.5 pl-5">
              <li>
                <strong className="text-slate-300">Stooq</strong> — free daily OHLCV history,
                used as the primary source for the 1M/3M/6M/1Y timeframes.
              </li>
              <li>
                <strong className="text-slate-300">Yahoo Finance's public chart endpoint</strong>{' '}
                — used for true intraday bars on the 1D/5D timeframes (Stooq's free tier is
                daily-only), and as a fallback if Stooq has no data for a symbol.
              </li>
            </ul>
            <p>
              Both are unauthenticated, undocumented-for-this-use public endpoints rather than
              licensed commercial data feeds. They are usually reliable but can occasionally
              lag, rate-limit, or be unavailable — when both fail, ChartPilot tells you plainly
              and falls back to the screenshot-only visual estimate instead of pretending to
              have data it doesn't.
            </p>
          </Section>

          <Section title="3. The technical-analysis engine">
            <p>Once real bars are available, ChartPilot computes, using standard textbook formulas:</p>
            <ul className="list-disc space-y-1.5 pl-5">
              <li><strong className="text-slate-300">Trend</strong> — SMA 20/50/200 stack plus swing-high/swing-low structure (higher-highs/higher-lows vs. lower-highs/lower-lows), detected via a fractal swing-point method.</li>
              <li><strong className="text-slate-300">Momentum</strong> — RSI(14) with Wilder smoothing, MACD(12,26,9) with crossover detection, and RSI/price divergence.</li>
              <li><strong className="text-slate-300">Volatility</strong> — ATR(14) and Bollinger Bands(20, 2σ), including squeeze detection (band width near recent lows).</li>
              <li><strong className="text-slate-300">Support/resistance</strong> — swing highs/lows clustered into zones by proximity, scored by touch count and recency.</li>
              <li><strong className="text-slate-300">Patterns</strong> — double top/bottom, resistance/support breakouts (with volume confirmation where available), Bollinger squeezes, MACD crossovers, and RSI divergence, each reported with its own confidence.</li>
              <li><strong className="text-slate-300">Fibonacci retracement</strong> — 23.6/38.2/50/61.8/78.6% levels off the most recent significant swing.</li>
            </ul>
            <p>
              All of this math lives in this project's <code className="rounded bg-panel2 px-1 py-0.5 text-[12px]">lib/</code> folder as
              plain, readable functions — there is no hidden model call in this step.
            </p>
          </Section>

          <Section title="4. Turning readings into a score">
            <p>
              Trend, RSI, MACD, and pattern signals are combined into a single −100…+100 score
              using fixed, documented weights (trend 40%, MACD 20%, patterns 25%, RSI 15%). The
              score maps to a Strong Bearish → Bearish → Neutral → Bullish → Strong Bullish
              label. There is no machine-learning model here to overfit or misbehave silently —
              you can read the exact formula in <code className="rounded bg-panel2 px-1 py-0.5 text-[12px]">lib/scorer.ts</code>.
            </p>
          </Section>

          <Section title="5. Confidence scoring — and why it's capped">
            <p>
              Confidence starts from data quality (real intraday/daily data scores much higher
              than a screenshot-only read), then adjusts for how much history was available and
              how many signals agree with each other. It is deliberately capped well below 100%
              — screenshot-only reads are capped at 40%, and even a full, real-data read is
              capped at 92% — because no free (or paid) tool can be certain about where a price
              goes next. A high number here means "the available evidence points one direction
              fairly consistently," never "this will happen."
            </p>
          </Section>

          <Section title="6. Limitations, honestly">
            <ul className="list-disc space-y-1.5 pl-5">
              <li>Free data sources can lag, be incomplete, or occasionally be wrong.</li>
              <li>OCR ticker detection can misread a symbol — always verify it.</li>
              <li>Screenshot-only visual analysis is a coarse heuristic, not real data extraction.</li>
              <li>Technical analysis describes patterns in past price action; it does not predict the future, and markets can and do invalidate any setup.</li>
              <li>This tool has no knowledge of your finances, goals, or risk tolerance, and does not account for fundamentals, news, or macro events.</li>
            </ul>
            <p className="pt-1">
              ChartPilot is built to be as transparent and mechanically sound as a free tool can
              be — not to claim certainty it can't have. Treat every plan as one structured
              opinion to weigh against your own judgment, not an instruction.
            </p>
          </Section>
        </div>
      </main>
      <Footer />
    </div>
  );
}
