export function Footer() {
  return (
    <footer className="border-t border-border mt-8">
      <div className="max-w-[1600px] mx-auto px-4 md:px-6 py-5 text-xs text-slate-500 leading-relaxed">
        <p>
          <strong className="text-slate-400">MemeMind AI is a simulation.</strong> Every coin, price, trade, and
          portfolio balance on this page is generated by an in-browser market model — there is no real exchange,
          wallet, or funds involved, and nothing here is investment advice. The "AI" is a lightweight online-learning
          trading policy (a linear contextual-bandit model updated after every closed trade) that runs entirely in
          your browser; its state is stored only in this browser's local storage.
        </p>
      </div>
    </footer>
  );
}
